# Домашнее задание № 1

## Задание 1 (2 балла)

Найдите 1 любой способ сломать токенизацию на предложения функцией sentenize из библиотеки razdel. Придумайте (или найдите на каком-то корпусе) такое предложение (или несколько предложений), которое будет некорректно разобрано sentenize, но при этом будет грамматически корректным.

In [21]:
from razdel import sentenize

text = '«Как же так?! Захар...» — воскликнут Пронин.'
for sent in sentenize(text):
    print(f"'{sent.text}'")

'«Как же так?!'
'Захар...» — воскликнут Пронин.'

## 2. Токенизация Mystem vs razdel.tokenize (2 балла)


Токенизируйте текст с помощью razdel и с помощью Mystem. Найдите различия в токенизациях. Что по вашему работает лучше на приведенном тексте?

### Как мне кажется, для токенизации лучше использовать razdel, так как он лучше справился с числительными и дефисами (в случаее этого текста). Если требуется встроенная нормализация или анализ можно использовать Mystem.

In [35]:
text = """
Вторым и третьим открытыми белыми карликами стали Сириус B и Процион B. В 1844 году директор Кёнигсбергской обсерватории Фридрих Бессель, анализируя данные наблюдений, которые велись с 1755 года, обнаружил, что Сириус, ярчайшая звезда земного неба, и Процион периодически, хотя и весьма слабо, отклоняются от прямолинейной траектории движения по небесной сфере[5]. Бессель пришёл к выводу, что у каждой из них должен быть близкий спутник. Сообщение было встречено скептически, поскольку слабый спутник оставался ненаблюдаемым, а его масса должна была быть достаточно велика — сравнимой с массой Сириуса и Проциона, соответственно.

В январе 1862 года Элвин Грэхэм Кларк, юстируя 18-дюймовый рефрактор, самый большой на то время телескоп в мире (Dearborn Telescope), впоследствии поставленный семейной фирмой Кларков в обсерваторию Чикагского университета, обнаружил в непосредственной близости от Сириуса тусклую звёздочку. Это был спутник Сириуса, Сириус B, предсказанный Бесселем[6]. А в 1896 году американский астроном Д. М. Шеберле открыл Процион B, подтвердив тем самым и второе предсказание Бесселя.

В 1915 году американский астроном Уолтер Сидней Адамс измерил спектр Сириуса B. Из измерений следовало, что его температура не ниже, чем у Сириуса A (по современным данным, температура поверхности Сириуса B составляет 25 000 K, а Сириуса A — 10 000 К), что, с учётом его в 10 000 раз меньшей, чем у Сириуса A, светимости указывает на очень малый радиус и, соответственно, высокую плотность — 106 г/см3 (плотность Сириуса ~0,25 г/см3, плотность Солнца ~1,4 г/см3).
"""

In [49]:
from razdel import tokenize as razdel_tokenize
from pymystem3 import Mystem

mystem = Mystem(disambiguation=False)

In [37]:
razdel_tokens = []
for token in razdel_tokenize(text):
    razdel_tokens.append(token.text)
    print({token.text})

{'Вторым'}
{'и'}
{'третьим'}
{'открытыми'}
{'белыми'}
{'карликами'}
{'стали'}
{'Сириус'}
{'B'}
{'и'}
{'Процион'}
{'B'}
{'.'}
{'В'}
{'1844'}
{'году'}
{'директор'}
{'Кёнигсбергской'}
{'обсерватории'}
{'Фридрих'}
{'Бессель'}
{','}
{'анализируя'}
{'данные'}
{'наблюдений'}
{','}
{'которые'}
{'велись'}
{'с'}
{'1755'}
{'года'}
{','}
{'обнаружил'}
{','}
{'что'}
{'Сириус'}
{','}
{'ярчайшая'}
{'звезда'}
{'земного'}
{'неба'}
{','}
{'и'}
{'Процион'}
{'периодически'}
{','}
{'хотя'}
{'и'}
{'весьма'}
{'слабо'}
{','}
{'отклоняются'}
{'от'}
{'прямолинейной'}
{'траектории'}
{'движения'}
{'по'}
{'небесной'}
{'сфере'}
{'['}
{'5'}
{']'}
{'.'}
{'Бессель'}
{'пришёл'}
{'к'}
{'выводу'}
{','}
{'что'}
{'у'}
{'каждой'}
{'из'}
{'них'}
{'должен'}
{'быть'}
{'близкий'}
{'спутник'}
{'.'}
{'Сообщение'}
{'было'}
{'встречено'}
{'скептически'}
{','}
{'поскольку'}
{'слабый'}
{'спутник'}
{'оставался'}
{'ненаблюдаемым'}
{','}
{'а'}
{'его'}
{'масса'}
{'должна'}
{'была'}
{'быть'}
{'достаточно'}
{'велика'}
{'—'}
{'сравнимой'}
{'с'}
{'массой'}
{'Сириуса'}
{'и'}
{'Проциона'}
{','}
{'соответственно'}
{'.'}
{'В'}
{'январе'}
{'1862'}
{'года'}
{'Элвин'}
{'Грэхэм'}
{'Кларк'}
{','}
{'юстируя'}
{'18-дюймовый'}
{'рефрактор'}
{','}
{'самый'}
{'большой'}
{'на'}
{'то'}
{'время'}
{'телескоп'}
{'в'}
{'мире'}
{'('}
{'Dearborn'}
{'Telescope'}
{')'}
{','}
{'впоследствии'}
{'поставленный'}
{'семейной'}
{'фирмой'}
{'Кларков'}
{'в'}
{'обсерваторию'}
{'Чикагского'}
{'университета'}
{','}
{'обнаружил'}
{'в'}
{'непосредственной'}
{'близости'}
{'от'}
{'Сириуса'}
{'тусклую'}
{'звёздочку'}
{'.'}
{'Это'}
{'был'}
{'спутник'}
{'Сириуса'}
{','}
{'Сириус'}
{'B'}
{','}
{'предсказанный'}
{'Бесселем'}
{'['}
{'6'}
{']'}
{'.'}
{'А'}
{'в'}
{'1896'}
{'году'}
{'американский'}
{'астроном'}
{'Д'}
{'.'}
{'М'}
{'.'}
{'Шеберле'}
{'открыл'}
{'Процион'}
{'B'}
{','}
{'подтвердив'}
{'тем'}
{'самым'}
{'и'}
{'второе'}
{'предсказание'}
{'Бесселя'}
{'.'}
{'В'}
{'1915'}
{'году'}
{'американский'}
{'астроном'}
{'Уолтер'}
{'Сидней'}
{'Адамс'}
{'измерил'}
{'спектр'}
{'Сириуса'}
{'B'}
{'.'}
{'Из'}
{'измерений'}
{'следовало'}
{','}
{'что'}
{'его'}
{'температура'}
{'не'}
{'ниже'}
{','}
{'чем'}
{'у'}
{'Сириуса'}
{'A'}
{'('}
{'по'}
{'современным'}
{'данным'}
{','}
{'температура'}
{'поверхности'}
{'Сириуса'}
{'B'}
{'составляет'}
{'25'}
{'000'}
{'K'}
{','}
{'а'}
{'Сириуса'}
{'A'}
{'—'}
{'10'}
{'000'}
{'К'}
{')'}
{','}
{'что'}
{','}
{'с'}
{'учётом'}
{'его'}
{'в'}
{'10'}
{'000'}
{'раз'}
{'меньшей'}
{','}
{'чем'}
{'у'}
{'Сириуса'}
{'A'}
{','}
{'светимости'}
{'указывает'}
{'на'}
{'очень'}
{'малый'}
{'радиус'}
{'и'}
{','}
{'соответственно'}
{','}
{'высокую'}
{'плотность'}
{'—'}
{'106'}
{'г'}
{'/'}
{'см'}
{'3'}
{'('}
{'плотность'}
{'Сириуса'}
{'~'}
{'0,25'}
{'г'}
{'/'}
{'см'}
{'3'}
{','}
{'плотность'}
{'Солнца'}
{'~'}
{'1,4'}
{'г'}
{'/'}
{'см'}
{'3'}
{')'}
{'.'}

In [51]:
mystem_tokens_raw

[{'text': '\n'},
 {'analysis': [{'lex': 'второй',
    'wt': 0.986135184,
    'gr': 'ANUM=(дат,мн|твор,ед,муж|твор,ед,сред)'},
   {'lex': 'второе',
    'wt': 0.01386481599,
    'gr': 'S,сред,неод=(дат,мн|твор,ед)'}],
  'text': 'Вторым'},
 {'text': ' '},
 {'analysis': [{'lex': 'и', 'wt': 0.9999770357, 'gr': 'CONJ='},
   {'lex': 'и', 'wt': 1.020511514e-05, 'gr': 'INTJ='},
   {'lex': 'и',
    'wt': 6.379604644e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'},
   {'lex': 'и', 'wt': 6.37957056e-06, 'gr': 'PART='}],
  'text': 'и'},
 {'text': ' '},
 {'analysis': [{'lex': 'третий',
    'wt': 0.9944396734,
    'gr': 'ANUM=(дат,мн|твор,ед,муж|твор,ед,сред)'},
   {'lex': 'третье',
    'wt': 0.005203241379,
    'gr': 'S,сред,неод=(дат,мн|твор,ед)'},
   {'lex': 'третья', 'wt': 0.0003570851927, 'gr': 'S,жен,неод=дат,мн'}],
  'text': 'третьим'},
 {'text': ' '},
 {'analysis': [{'lex': 'открытый', 'wt': 0.959315763, 'gr': 'A=твор,мн,полн'},
   {'lex': 'открывать',
    'wt': 0.04068423698,
    'gr': 'V=прош,твор,мн,прич,полн,сов,страд'}],
  'text': 'открытыми'},
 {'text': ' '},
 {'analysis': [{'lex': 'белый', 'wt': 0.9932845421, 'gr': 'A=твор,мн,полн'},
   {'lex': 'белый', 'wt': 0.004325486119, 'gr': 'S,фам,муж,од=твор,мн'},
   {'lex': 'белые', 'wt': 0.001358058754, 'gr': 'S,мн,неод=твор'},
   {'lex': 'белые', 'wt': 0.001031912979, 'gr': 'S,мн,од=твор'},
   {'lex': 'белая', 'wt': 0, 'gr': 'S,фам,жен,од=твор,мн'}],
  'text': 'белыми'},
 {'text': ' '},
 {'analysis': [{'lex': 'карлик', 'wt': 1, 'gr': 'S,муж,од=твор,мн'}],
  'text': 'карликами'},
 {'text': ' '},
 {'analysis': [{'lex': 'становиться',
    'wt': 0.9821285244,
    'gr': 'V,нп=прош,мн,изъяв,сов'},
   {'lex': 'сталь',
    'wt': 0.01787147557,
    'gr': 'S,жен,неод=(пр,ед|вин,мн|дат,ед|род,ед|им,мн)'}],
  'text': 'стали'},
 {'text': ' '},
 {'analysis': [{'lex': 'сириус',
    'wt': 1,
    'gr': 'S,гео,муж,неод=(вин,ед|им,ед)'}],
  'text': 'Сириус'},
 {'text': ' '},
 {'analysis': [], 'text': 'B'},
 {'text': ' '},
 {'analysis': [{'lex': 'и', 'wt': 0.9999770357, 'gr': 'CONJ='},
   {'lex': 'и', 'wt': 1.020511514e-05, 'gr': 'INTJ='},
   {'lex': 'и',
    'wt': 6.379604644e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'},
   {'lex': 'и', 'wt': 6.37957056e-06, 'gr': 'PART='}],
  'text': 'и'},
 {'text': ' '},
 {'analysis': [{'lex': 'процион',
    'wt': 1,
    'qual': 'bastard',
    'gr': 'S,муж,неод=(вин,ед|им,ед)'}],
  'text': 'Процион'},
 {'text': ' '},
 {'analysis': [], 'text': 'B'},
 {'text': '. '},
 {'analysis': [{'lex': 'в', 'wt': 0.9999917878, 'gr': 'PR='},
   {'lex': 'в',
    'wt': 8.212235587e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'В'},
 {'text': ' '},
 {'text': '1844'},
 {'text': ' '},
 {'analysis': [{'lex': 'год', 'wt': 1, 'gr': 'S,муж,неод=(дат,ед|местн,ед)'}],
  'text': 'году'},
 {'text': ' '},
 {'analysis': [{'lex': 'директор', 'wt': 1, 'gr': 'S,муж,од=им,ед'}],
  'text': 'директор'},
 {'text': ' '},
 {'analysis': [{'lex': 'кенигсбергский',
    'wt': 1,
    'gr': 'A=(пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'Кёнигсбергской'},
 {'text': ' '},
 {'analysis': [{'lex': 'обсерватория',
    'wt': 1,
    'gr': 'S,жен,неод=(пр,ед|вин,мн|дат,ед|род,ед|им,мн)'}],
  'text': 'обсерватории'},
 {'text': ' '},
 {'analysis': [{'lex': 'фридрих', 'wt': 1, 'gr': 'S,имя,муж,од=им,ед'}],
  'text': 'Фридрих'},
 {'text': ' '},
 {'analysis': [{'lex': 'бессель', 'wt': 1, 'gr': 'S,имя,муж,од=им,ед'}],
  'text': 'Бессель'},
 {'text': ', '},
 {'analysis': [{'lex': 'анализировать',
    'wt': 1,
    'gr': 'V,несов,пе=непрош,деепр'}],
  'text': 'анализируя'},
 {'text': ' '},
 {'analysis': [{'lex': 'данные',
    'wt': 0.8760081205,
    'gr': 'S,мн,неод=(вин|им)'},
   {'lex': 'давать',
    'wt': 0.1239292426,
    'gr': 'V,пе=(прош,вин,мн,прич,полн,сов,страд,неод|прош,им,мн,прич,полн,сов,страд)'},
   {'lex': 'данный',
    'wt': 6.263687536e-05,
    'gr': 'A,полн=(им,мн|вин,мн,неод)'}],
  'text': 'данные'},
 {'text': ' '},
 {'analysis': [{'lex': 'наблюдение', 'wt': 1, 'gr': 'S,сред,неод=род,мн'}],
  'text': 'наблюдений'},
 {'text': ', '},
 {'analysis': [{'lex': 'который', 'wt': 1, 'gr': 'APRO=(им,мн|вин,мн,неод)'}],
  'text': 'которые'},
 {'text': ' '},
 {'analysis': [{'lex': 'вестись',
    'wt': 0.5361965901,
    'gr': 'V,несов,нп=прош,мн,изъяв'},
   {'lex': 'вестись', 'wt': 0.4638034099, 'gr': 'V,несов,нп=прош,мн,изъяв'}],
  'text': 'велись'},
 {'text': ' '},
 {'analysis': [{'lex': 'с', 'wt': 0.999977831, 'gr': 'PR='},
   {'lex': 'с',
    'wt': 2.216901809e-05,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'с'},
 {'text': ' '},
 {'text': '1755'},
 {'text': ' '},
 {'analysis': [{'lex': 'год',
    'wt': 1,
    'gr': 'S,муж,неод=(вин,мн|род,ед|им,мн)'}],
  'text': 'года'},
 {'text': ', '},
 {'analysis': [{'lex': 'обнаруживать',
    'wt': 1,
    'gr': 'V,пе=прош,ед,изъяв,муж,сов'}],
  'text': 'обнаружил'},
 {'text': ', '},
 {'analysis': [{'lex': 'что', 'wt': 0.688532576, 'gr': 'CONJ='},
   {'lex': 'что', 'wt': 0.2934446278, 'gr': 'SPRO,ед,сред,неод=(вин|им)'},
   {'lex': 'что', 'wt': 0.01802279617, 'gr': 'ADVPRO='}],
  'text': 'что'},
 {'text': ' '},
 {'analysis': [{'lex': 'сириус',
    'wt': 1,
    'gr': 'S,гео,муж,неод=(вин,ед|им,ед)'}],
  'text': 'Сириус'},
 {'text': ', '},
 {'analysis': [{'lex': 'яркий', 'wt': 1, 'gr': 'A=им,ед,полн,прев,жен'}],
  'text': 'ярчайшая'},
 {'text': ' '},
 {'analysis': [{'lex': 'звезда', 'wt': 0.690962732, 'gr': 'S,жен,неод=им,ед'},
   {'lex': 'звезда', 'wt': 0.309037268, 'gr': 'S,жен,од=им,ед'}],
  'text': 'звезда'},
 {'text': ' '},
 {'analysis': [{'lex': 'земной',
    'wt': 1,
    'gr': 'A=(вин,ед,полн,муж,од|род,ед,полн,муж|род,ед,полн,сред)'}],
  'text': 'земного'},
 {'text': ' '},
 {'analysis': [{'lex': 'небо',
    'wt': 0.5986169838,
    'gr': 'S,сред,неод=(вин,мн|род,ед|им,мн)'},
   {'lex': 'небо', 'wt': 0.4013830162, 'gr': 'S,сред,неод=род,ед'}],
  'text': 'неба'},
 {'text': ', '},
 {'analysis': [{'lex': 'и', 'wt': 0.9999770357, 'gr': 'CONJ='},
   {'lex': 'и', 'wt': 1.020511514e-05, 'gr': 'INTJ='},
   {'lex': 'и',
    'wt': 6.379604644e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'},
   {'lex': 'и', 'wt': 6.37957056e-06, 'gr': 'PART='}],
  'text': 'и'},
 {'text': ' '},
 {'analysis': [{'lex': 'процион',
    'wt': 1,
    'qual': 'bastard',
    'gr': 'S,муж,неод=(вин,ед|им,ед)'}],
  'text': 'Процион'},
 {'text': ' '},
 {'analysis': [{'lex': 'периодически', 'wt': 0.9999489765, 'gr': 'ADV='},
   {'lex': 'периодический', 'wt': 5.102349973e-05, 'gr': 'A=мн,кр'}],
  'text': 'периодически'},
 {'text': ', '},
 {'analysis': [{'lex': 'хотя', 'wt': 0.7674314765, 'gr': 'CONJ='},
   {'lex': 'хотя', 'wt': 0.2317662576, 'gr': 'PART='},
   {'lex': 'хотеть', 'wt': 0.0008022659392, 'gr': 'V,несов,пе=непрош,деепр'}],
  'text': 'хотя'},
 {'text': ' '},
 {'analysis': [{'lex': 'и', 'wt': 0.9999770357, 'gr': 'CONJ='},
   {'lex': 'и', 'wt': 1.020511514e-05, 'gr': 'INTJ='},
   {'lex': 'и',
    'wt': 6.379604644e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'},
   {'lex': 'и', 'wt': 6.37957056e-06, 'gr': 'PART='}],
  'text': 'и'},
 {'text': ' '},
 {'analysis': [{'lex': 'весьма', 'wt': 1, 'gr': 'ADV='}], 'text': 'весьма'},
 {'text': ' '},
 {'analysis': [{'lex': 'слабо', 'wt': 0.9235434159, 'gr': 'ADV='},
   {'lex': 'слабый', 'wt': 0.04218115014, 'gr': 'A=ед,кр,сред'},
   {'lex': 'слабо', 'wt': 0.03427543392, 'gr': 'ADV,прдк='}],
  'text': 'слабо'},
 {'text': ', '},
 {'analysis': [{'lex': 'отклоняться',
    'wt': 1,
    'gr': 'V,нп=непрош,мн,изъяв,3-л,несов'}],
  'text': 'отклоняются'},
 {'text': ' '},
 {'analysis': [{'lex': 'от', 'wt': 1, 'gr': 'PR='}], 'text': 'от'},
 {'text': ' '},
 {'analysis': [{'lex': 'прямолинейный',
    'wt': 1,
    'gr': 'A=(пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'прямолинейной'},
 {'text': ' '},
 {'analysis': [{'lex': 'траектория',
    'wt': 1,
    'gr': 'S,жен,неод=(пр,ед|вин,мн|дат,ед|род,ед|им,мн)'}],
  'text': 'траектории'},
 {'text': ' '},
 {'analysis': [{'lex': 'движение',
    'wt': 1,
    'gr': 'S,сред,неод=(вин,мн|род,ед|им,мн)'}],
  'text': 'движения'},
 {'text': ' '},
 {'analysis': [{'lex': 'по', 'wt': 1, 'gr': 'PR='}], 'text': 'по'},
 {'text': ' '},
 {'analysis': [{'lex': 'небесный',
    'wt': 1,
    'gr': 'A=(пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'небесной'},
 {'text': ' '},
 {'analysis': [{'lex': 'сфера', 'wt': 1, 'gr': 'S,жен,неод=(пр,ед|дат,ед)'}],
  'text': 'сфере'},
 {'text': '['},
 {'text': '5'},
 {'text': ']'},
 {'text': '. '},
 {'analysis': [{'lex': 'бессель', 'wt': 1, 'gr': 'S,имя,муж,од=им,ед'}],
  'text': 'Бессель'},
 {'text': ' '},
 {'analysis': [{'lex': 'приходить',
    'wt': 0.9984379383,
    'gr': 'V,нп=прош,ед,изъяв,муж,сов'},
   {'lex': 'прийти',
    'wt': 0.001562061663,
    'gr': 'V,сов,нп=прош,ед,изъяв,муж'}],
  'text': 'пришёл'},
 {'text': ' '},
 {'analysis': [{'lex': 'к', 'wt': 0.9999551798, 'gr': 'PR='},
   {'lex': 'к',
    'wt': 4.48202392e-05,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'к'},
 {'text': ' '},
 {'analysis': [{'lex': 'вывод', 'wt': 1, 'gr': 'S,муж,неод=дат,ед'}],
  'text': 'выводу'},
 {'text': ', '},
 {'analysis': [{'lex': 'что', 'wt': 0.688532576, 'gr': 'CONJ='},
   {'lex': 'что', 'wt': 0.2934446278, 'gr': 'SPRO,ед,сред,неод=(вин|им)'},
   {'lex': 'что', 'wt': 0.01802279617, 'gr': 'ADVPRO='}],
  'text': 'что'},
 {'text': ' '},
 {'analysis': [{'lex': 'у', 'wt': 0.9993940324, 'gr': 'PR='},
   {'lex': 'у', 'wt': 0.0005503630598, 'gr': 'INTJ='},
   {'lex': 'у',
    'wt': 5.560449756e-05,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'у'},
 {'text': ' '},
 {'analysis': [{'lex': 'каждый',
    'wt': 0.9971198475,
    'gr': 'APRO=(пр,ед,жен|дат,ед,жен|род,ед,жен|твор,ед,жен)'},
   {'lex': 'каждая',
    'wt': 0.002880152466,
    'gr': 'S,ед,жен,од=(пр|дат|род|твор)'}],
  'text': 'каждой'},
 {'text': ' '},
 {'analysis': [{'lex': 'из', 'wt': 0.9999999775, 'gr': 'PR='},
   {'lex': 'иза',
    'wt': 2.252302755e-08,
    'gr': 'S,имя,жен,од=(вин,мн|род,мн)'}],
  'text': 'из'},
 {'text': ' '},
 {'analysis': [{'lex': 'они', 'wt': 1, 'gr': 'SPRO,мн=(пр|вин|род)'}],
  'text': 'них'},
 {'text': ' '},
 {'analysis': [{'lex': 'должный', 'wt': 1, 'gr': 'A=ед,кр,муж'}],
  'text': 'должен'},
 {'text': ' '},
 {'analysis': [{'lex': 'быть', 'wt': 1, 'gr': 'V,нп=инф,несов'}],
  'text': 'быть'},
 {'text': ' '},
 {'analysis': [{'lex': 'близкий',
    'wt': 1,
    'gr': 'A=(вин,ед,полн,муж,неод|им,ед,полн,муж)'}],
  'text': 'близкий'},
 {'text': ' '},
 {'analysis': [{'lex': 'спутник',
    'wt': 1,
    'gr': 'S,муж=(им,ед,од|вин,ед,неод|им,ед,неод)'}],
  'text': 'спутник'},
 {'text': '. '},
 {'analysis': [{'lex': 'сообщение',
    'wt': 1,
    'gr': 'S,сред,неод=(вин,ед|им,ед)'}],
  'text': 'Сообщение'},
 {'text': ' '},
 {'analysis': [{'lex': 'быть',
    'wt': 0.975680698,
    'gr': 'V,нп=прош,ед,изъяв,сред,несов'},
   {'lex': 'было', 'wt': 0.02431930199, 'gr': 'PART='}],
  'text': 'было'},
 {'text': ' '},
 {'analysis': [{'lex': 'встречать',
    'wt': 1,
    'gr': 'V,пе=прош,ед,прич,кр,сред,сов,страд'}],
  'text': 'встречено'},
 {'text': ' '},
 {'analysis': [{'lex': 'скептически', 'wt': 0.9999643443, 'gr': 'ADV='},
   {'lex': 'скептический', 'wt': 3.565566181e-05, 'gr': 'A=мн,кр'}],
  'text': 'скептически'},
 {'text': ', '},
 {'analysis': [{'lex': 'поскольку', 'wt': 1, 'gr': 'CONJ='}],
  'text': 'поскольку'},
 {'text': ' '},
 {'analysis': [{'lex': 'слабый',
    'wt': 1,
    'gr': 'A=(вин,ед,полн,муж,неод|им,ед,полн,муж)'}],
  'text': 'слабый'},
 {'text': ' '},
 {'analysis': [{'lex': 'спутник',
    'wt': 1,
    'gr': 'S,муж=(им,ед,од|вин,ед,неод|им,ед,неод)'}],
  'text': 'спутник'},
 {'text': ' '},
 {'analysis': [{'lex': 'оставаться',
    'wt': 1,
    'gr': 'V,нп=прош,ед,изъяв,муж,несов'}],
  'text': 'оставался'},
 {'text': ' '},
 {'analysis': [{'lex': 'ненаблюдаемый',
    'wt': 1,
    'gr': 'A,полн=(дат,мн|твор,ед,муж|твор,ед,сред)'}],
  'text': 'ненаблюдаемым'},
 {'text': ', '},
 {'analysis': [{'lex': 'а', 'wt': 0.9822148501, 'gr': 'CONJ='},
   {'lex': 'а', 'wt': 0.01124958978, 'gr': 'PART='},
   {'lex': 'а', 'wt': 0.006507707532, 'gr': 'INTJ='},
   {'lex': 'а',
    'wt': 2.785256224e-05,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'а'},
 {'text': ' '},
 {'analysis': [{'lex': 'он',
    'wt': 0.9242062374,
    'gr': 'SPRO,ед,3-л,муж=(вин|род)'},
   {'lex': 'оно', 'wt': 0.07576092179, 'gr': 'SPRO,ед,3-л,сред=(вин|род)'},
   {'lex': 'его',
    'wt': 3.284086391e-05,
    'gr': 'APRO=(пр,мн|дат,мн|род,мн|твор,мн|им,мн|им,ед,жен|вин,ед,муж,од|род,ед,муж|род,ед,сред|вин,ед,сред|им,ед,сред|пр,ед,жен|дат,ед,жен|род,ед,жен|твор,ед,жен|пр,ед,муж|пр,ед,сред|дат,ед,муж|дат,ед,сред|вин,ед,жен|вин,мн,неод|вин,ед,муж,неод|им,ед,муж|твор,ед,муж|твор,ед,сред|вин,мн,од|пр,мн,сред|вин,мн,сред|дат,мн,сред|род,мн,сред|твор,мн,сред|им,мн,сред|пр,мн,муж|вин,мн,муж|вин,ед,муж|дат,мн,муж)'}],
  'text': 'его'},
 {'text': ' '},
 {'analysis': [{'lex': 'масса', 'wt': 1, 'gr': 'S,жен,неод=им,ед'}],
  'text': 'масса'},
 {'text': ' '},
 {'analysis': [{'lex': 'должный', 'wt': 1, 'gr': 'A=ед,кр,жен'}],
  'text': 'должна'},
 {'text': ' '},
 {'analysis': [{'lex': 'быть', 'wt': 1, 'gr': 'V,нп=прош,ед,изъяв,жен,несов'}],
  'text': 'была'},
 {'text': ' '},
 {'analysis': [{'lex': 'быть', 'wt': 1, 'gr': 'V,нп=инф,несов'}],
  'text': 'быть'},
 {'text': ' '},
 {'analysis': [{'lex': 'достаточно', 'wt': 0.591353536, 'gr': 'ADV='},
   {'lex': 'достаточно', 'wt': 0.4056356479, 'gr': 'ADV,прдк='},
   {'lex': 'достаточный', 'wt': 0.003010816092, 'gr': 'A=ед,кр,сред'}],
  'text': 'достаточно'},
 {'text': ' '},
 {'analysis': [{'lex': 'большой', 'wt': 0.9952426116, 'gr': 'A=ед,кр,жен'},
   {'lex': 'велик', 'wt': 0.004757388407, 'gr': 'S,муж,неод=род,ед'}],
  'text': 'велика'},
 {'text': ' — '},
 {'analysis': [{'lex': 'сравнимый',
    'wt': 1,
    'gr': 'A=(пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'сравнимой'},
 {'text': ' '},
 {'analysis': [{'lex': 'с', 'wt': 0.999977831, 'gr': 'PR='},
   {'lex': 'с',
    'wt': 2.216901809e-05,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'с'},
 {'text': ' '},
 {'analysis': [{'lex': 'масса', 'wt': 1, 'gr': 'S,жен,неод=твор,ед'}],
  'text': 'массой'},
 {'text': ' '},
 {'analysis': [{'lex': 'сириус', 'wt': 1, 'gr': 'S,гео,муж,неод=род,ед'}],
  'text': 'Сириуса'},
 {'text': ' '},
 {'analysis': [{'lex': 'и', 'wt': 0.9999770357, 'gr': 'CONJ='},
   {'lex': 'и', 'wt': 1.020511514e-05, 'gr': 'INTJ='},
   {'lex': 'и',
    'wt': 6.379604644e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'},
   {'lex': 'и', 'wt': 6.37957056e-06, 'gr': 'PART='}],
  'text': 'и'},
 {'text': ' '},
 {'analysis': [{'lex': 'процион',
    'wt': 1,
    'qual': 'bastard',
    'gr': 'S,муж,неод=род,ед'}],
  'text': 'Проциона'},
 {'text': ', '},
 {'analysis': [{'lex': 'соответственно', 'wt': 0.759490663, 'gr': 'ADV='},
   {'lex': 'соответственно', 'wt': 0.1943024544, 'gr': 'CONJ='},
   {'lex': 'соответственно', 'wt': 0.04571825844, 'gr': 'PR='},
   {'lex': 'соответственный', 'wt': 0.0004886241521, 'gr': 'A=ед,кр,сред'}],
  'text': 'соответственно'},
 {'text': '.'},
 {'text': '\n'},
 {'text': '\n'},
 {'analysis': [{'lex': 'в', 'wt': 0.9999917878, 'gr': 'PR='},
   {'lex': 'в',
    'wt': 8.212235587e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'В'},
 {'text': ' '},
 {'analysis': [{'lex': 'январь', 'wt': 0.9998020422, 'gr': 'S,муж,неод=пр,ед'},
   {'lex': 'январь', 'wt': 0.0001979578068, 'gr': 'S,имя,муж,од=пр,ед'}],
  'text': 'январе'},
 {'text': ' '},
 {'text': '1862'},
 {'text': ' '},
 {'analysis': [{'lex': 'год',
    'wt': 1,
    'gr': 'S,муж,неод=(вин,мн|род,ед|им,мн)'}],
  'text': 'года'},
 {'text': ' '},
 {'analysis': [{'lex': 'элвин', 'wt': 1, 'gr': 'S,имя,муж,од=им,ед'}],
  'text': 'Элвин'},
 {'text': ' '},
 {'analysis': [{'lex': 'грэхэм', 'wt': 1, 'gr': 'S,имя,муж,од=им,ед'}],
  'text': 'Грэхэм'},
 {'text': ' '},
 {'analysis': [{'lex': 'кларк',
    'wt': 0.6541957737,
    'gr': 'S,фам,муж,од=им,ед'},
   {'lex': 'кларк', 'wt': 0.1526664572, 'gr': 'S,муж,неод=(вин,ед|им,ед)'},
   {'lex': 'кларк', 'wt': 0.1295369716, 'gr': 'S,имя,муж,од=им,ед'},
   {'lex': 'кларк',
    'wt': 0.06360079742,
    'gr': 'S,фам,жен,од=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'Кларк'},
 {'text': ', '},
 {'analysis': [{'lex': 'юстировать',
    'wt': 1,
    'gr': 'V,пе=непрош,деепр,несов'}],
  'text': 'юстируя'},
 {'text': ' '},
 {'text': '18'},
 {'text': '-'},
 {'analysis': [{'lex': 'дюймовый',
    'wt': 1,
    'gr': 'A=(вин,ед,полн,муж,неод|им,ед,полн,муж)'}],
  'text': 'дюймовый'},
 {'text': ' '},
 {'analysis': [{'lex': 'рефрактор',
    'wt': 1,
    'gr': 'S,муж,неод=(вин,ед|им,ед)'}],
  'text': 'рефрактор'},
 {'text': ', '},
 {'analysis': [{'lex': 'самый',
    'wt': 1,
    'gr': 'APRO=(вин,ед,муж,неод|им,ед,муж)'}],
  'text': 'самый'},
 {'text': ' '},
 {'analysis': [{'lex': 'большой',
    'wt': 1,
    'gr': 'A=(вин,ед,полн,муж,неод|им,ед,полн,муж|пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'большой'},
 {'text': ' '},
 {'analysis': [{'lex': 'на', 'wt': 0.9989522965, 'gr': 'PR='},
   {'lex': 'на', 'wt': 0.00104770353, 'gr': 'PART='}],
  'text': 'на'},
 {'text': ' '},
 {'analysis': [{'lex': 'то',
    'wt': 0.4146576429,
    'gr': 'SPRO,ед,сред,неод=(вин|им)'},
   {'lex': 'то', 'wt': 0.3040701242, 'gr': 'CONJ='},
   {'lex': 'то', 'wt': 0.2640456945, 'gr': 'PART='},
   {'lex': 'тот', 'wt': 0.01722653842, 'gr': 'APRO=(вин,ед,сред|им,ед,сред)'}],
  'text': 'то'},
 {'text': ' '},
 {'analysis': [{'lex': 'время', 'wt': 1, 'gr': 'S,сред,неод=(вин,ед|им,ед)'}],
  'text': 'время'},
 {'text': ' '},
 {'analysis': [{'lex': 'телескоп',
    'wt': 1,
    'gr': 'S,муж,неод=(вин,ед|им,ед)'}],
  'text': 'телескоп'},
 {'text': ' '},
 {'analysis': [{'lex': 'в', 'wt': 0.9999917878, 'gr': 'PR='},
   {'lex': 'в',
    'wt': 8.212235587e-06,
    'gr': 'S,сокр=(пр,мн|пр,ед|вин,мн|вин,ед|дат,мн|дат,ед|род,мн|род,ед|твор,мн|твор,ед|им,мн|им,ед)'}],
  'text': 'в'},
 {'text': ' '},
 {'analysis': [{'lex': 'мир', 'wt': 0.9922263828, 'gr': 'S,муж,неод=пр,ед'},
   {'lex': 'мира', 'wt': 0.005259107883, 'gr': 'S,имя,жен,од=(пр,ед|дат,ед)'},
   {'lex': 'миро', 'wt': 0.001867024737, 'gr': 'S,сред,неод=пр,ед'},
   {'lex': 'мира', 'wt': 0.0006318144816, 'gr': 'S,жен,неод=(пр,ед|дат,ед)'},
   {'lex': 'мир', 'wt': 1.567008827e-05, 'gr': 'S,имя,муж,од=пр,ед'}],
  'text': 'мире'},
 {'text': ' ('},
 {'analysis': [], 'text': 'Dearborn'},
 {'text': ' '},
 {'analysis': [], 'text': 'Telescope'},
 {'text': '), '},
 {'analysis': [{'lex': 'впоследствии', 'wt': 1, 'gr': 'ADV='}],
  'text': 'впоследствии'},
 {'text': ' '},
 {'analysis': [{'lex': 'поставлять',
    'wt': 1,
    'gr': 'V,пе=(прош,вин,ед,прич,полн,муж,сов,страд,неод|прош,им,ед,прич,полн,муж,сов,страд)'}],
  'text': 'поставленный'},
 {'text': ' '},
 {'analysis': [{'lex': 'семейный',
    'wt': 1,
    'gr': 'A=(пр,ед,полн,жен|дат,ед,полн,жен|род,ед,полн,жен|твор,ед,полн,жен)'}],
  'text': 'семейной'},
 {'text': ' '},
 {'analysis': [{'lex': 'фирма', 'wt': 1, 'gr': 'S,жен,неод=твор,ед'}],
  'text': 'фирмой'},
 {'text': ' '},
 {'analysis': [{'lex': 'кларк', 'wt': 0.6997748608, 'gr': 'S,муж,неод=род,мн'},
   {'lex': 'кларк', 'wt': 0.2912571399, 'gr': 'S,фам,муж,од=(вин,мн|род,мн)'},

In [56]:
mystem_tokens_raw = mystem.analyze(text)
mystem_tokens = []

for item in mystem_tokens_raw:
    token_text = item['text'].strip()
    if token_text:
        mystem_tokens.append(token_text)

for token in mystem_tokens:
    print(f"'{token}'")

'Вторым'
'и'
'третьим'
'открытыми'
'белыми'
'карликами'
'стали'
'Сириус'
'B'
'и'
'Процион'
'B'
'.'
'В'
'1844'
'году'
'директор'
'Кёнигсбергской'
'обсерватории'
'Фридрих'
'Бессель'
','
'анализируя'
'данные'
'наблюдений'
','
'которые'
'велись'
'с'
'1755'
'года'
','
'обнаружил'
','
'что'
'Сириус'
','
'ярчайшая'
'звезда'
'земного'
'неба'
','
'и'
'Процион'
'периодически'
','
'хотя'
'и'
'весьма'
'слабо'
','
'отклоняются'
'от'
'прямолинейной'
'траектории'
'движения'
'по'
'небесной'
'сфере'
'['
'5'
']'
'.'
'Бессель'
'пришёл'
'к'
'выводу'
','
'что'
'у'
'каждой'
'из'
'них'
'должен'
'быть'
'близкий'
'спутник'
'.'
'Сообщение'
'было'
'встречено'
'скептически'
','
'поскольку'
'слабый'
'спутник'
'оставался'
'ненаблюдаемым'
','
'а'
'его'
'масса'
'должна'
'была'
'быть'
'достаточно'
'велика'
'—'
'сравнимой'
'с'
'массой'
'Сириуса'
'и'
'Проциона'
','
'соответственно'
'.'
'В'
'январе'
'1862'
'года'
'Элвин'
'Грэхэм'
'Кларк'
','
'юстируя'
'18'
'-'
'дюймовый'
'рефрактор'
','
'самый'
'большой'
'на'
'то'
'время'
'телескоп'
'в'
'мире'
'('
'Dearborn'
'Telescope'
'),'
'впоследствии'
'поставленный'
'семейной'
'фирмой'
'Кларков'
'в'
'обсерваторию'
'Чикагского'
'университета'
','
'обнаружил'
'в'
'непосредственной'
'близости'
'от'
'Сириуса'
'тусклую'
'звёздочку'
'.'
'Это'
'был'
'спутник'
'Сириуса'
','
'Сириус'
'B'
','
'предсказанный'
'Бесселем'
'['
'6'
']'
'.'
'А'
'в'
'1896'
'году'
'американский'
'астроном'
'Д'
'.'
'М'
'.'
'Шеберле'
'открыл'
'Процион'
'B'
','
'подтвердив'
'тем'
'самым'
'и'
'второе'
'предсказание'
'Бесселя'
'.'
'В'
'1915'
'году'
'американский'
'астроном'
'Уолтер'
'Сидней'
'Адамс'
'измерил'
'спектр'
'Сириуса'
'B'
'.'
'Из'
'измерений'
'следовало'
','
'что'
'его'
'температура'
'не'
'ниже'
','
'чем'
'у'
'Сириуса'
'A'
'('
'по'
'современным'
'данным'
','
'температура'
'поверхности'
'Сириуса'
'B'
'составляет'
'25'
'000'
'K'
','
'а'
'Сириуса'
'A'
'—'
'10'
'000'
'К'
'),'
'что'
','
'с'
'учётом'
'его'
'в'
'10'
'000'
'раз'
'меньшей'
','
'чем'
'у'
'Сириуса'
'A'
','
'светимости'
'указывает'
'на'
'очень'
'малый'
'радиус'
'и'
','
'соответственно'
','
'высокую'
'плотность'
'—'
'106'
'г'
'/'
'см3'
'('
'плотность'
'Сириуса'
'~'
'0'
','
'25'
'г'
'/'
'см3'
','
'плотность'
'Солнца'
'~'
'1'
','
'4'
'г'
'/'
'см3'
')'
'.'

In [57]:
print(f"Razdel tokens: {len(razdel_tokens)}")
print(f"Mystem tokens: {len(mystem_tokens)}")

Razdel tokens: 292
Mystem tokens: 293

In [71]:
razdel_set = set(token.lower() for token in razdel_tokens)
mystem_set = set(token.lower() for token in mystem_tokens)

print("Сравнение уникальных токенов")

only_razdel = razdel_set - mystem_set
print(f"\nТокены только в Razdel ({len(only_razdel)}):")
for token in sorted(only_razdel):
    if token: 
        print(token)

only_mystem = mystem_set - razdel_set
print(f"\nТокены только в Mystem ({len(only_mystem)}):")
for token in sorted(only_mystem):
    if token:
        print(token)

Сравнение уникальных токенов

Токены только в Razdel (5):
0,25
1,4
18-дюймовый
3
см

Токены только в Mystem (8):
),
-
0
1
18
4
дюймовый
см3

## 3. Лемматизация Mystem vs Pymorphy (2 балла)

Лемматизируйте текст с помощью mystem и pymorphy. Найдите различия в лемматизации. Что по вашему работает лучше на приведенном тексте?

Важно: для пайморфи используйте токенизацию из mystem, чтобы исключить влияние токенизации на результат. Анализируйте только значимые различия, а не технические особенности (не сравнивайте скорость работы и удобность интерфейса).

В майстеме убедитесь, что используется дизамбигуация.

In [72]:

from pymorphy3 import MorphAnalyzer

mystem = Mystem(disambiguation=True)
morph = MorphAnalyzer()

In [73]:
mystem_tokens_raw = mystem.analyze(text)
tokens = []

for item in mystem_tokens_raw:
    if 'text' in item and item['text'].strip():
        tokens.append(item['text'].strip())

In [74]:
mystem_lemmas = []
for item in mystem_tokens_raw:
    if 'analysis' in item and item['analysis']:
        lemma = item['analysis'][0]['lex']
    elif 'text' in item:
        lemma = item['text']
    else:
        lemma = ''
    if lemma.strip():
        mystem_lemmas.append(lemma.strip())

In [76]:
mystem_lemmas

['второй',
 'и',
 'третий',
 'открытый',
 'белый',
 'карлик',
 'становиться',
 'сириус',
 'B',
 'и',
 'процион',
 'B',
 '.',
 'в',
 '1844',
 'год',
 'директор',
 'кенигсбергский',
 'обсерватория',
 'фридрих',
 'бессель',
 ',',
 'анализировать',
 'данные',
 'наблюдение',
 ',',
 'который',
 'вестись',
 'с',
 '1755',
 'год',
 ',',
 'обнаруживать',
 ',',
 'что',
 'сириус',
 ',',
 'яркий',
 'звезда',
 'земной',
 'небо',
 ',',
 'и',
 'процион',
 'периодически',
 ',',
 'хотя',
 'и',
 'весьма',
 'слабо',
 ',',
 'отклоняться',
 'от',
 'прямолинейный',
 'траектория',
 'движение',
 'по',
 'небесный',
 'сфера',
 '[',
 '5',
 ']',
 '.',
 'бессель',
 'приходить',
 'к',
 'вывод',
 ',',
 'что',
 'у',
 'каждый',
 'из',
 'они',
 'должный',
 'быть',
 'близкий',
 'спутник',
 '.',
 'сообщение',
 'быть',
 'встречать',
 'скептически',
 ',',
 'поскольку',
 'слабый',
 'спутник',
 'оставаться',
 'ненаблюдаемый',
 ',',
 'а',
 'его',
 'масса',
 'должный',
 'быть',
 'быть',
 'достаточно',
 'большой',
 '—',
 'сравнимый',
 'с',
 'масса',
 'сириус',
 'и',
 'процион',
 ',',
 'соответственно',
 '.',
 'в',
 'январь',
 '1862',
 'год',
 'элвин',
 'грэхэм',
 'кларк',
 ',',
 'юстировать',
 '18',
 '-',
 'дюймовый',
 'рефрактор',
 ',',
 'самый',
 'большой',
 'на',
 'то',
 'время',
 'телескоп',
 'в',
 'мир',
 '(',
 'Dearborn',
 'Telescope',
 '),',
 'впоследствии',
 'поставлять',
 'семейный',
 'фирма',
 'кларк',
 'в',
 'обсерватория',
 'чикагский',
 'университет',
 ',',
 'обнаруживать',
 'в',
 'непосредственный',
 'близость',
 'от',
 'сириус',
 'тусклый',
 'звездочка',
 '.',
 'это',
 'быть',
 'спутник',
 'сириус',
 ',',
 'сириус',
 'B',
 ',',
 'предсказывать',
 'бессель',
 '[',
 '6',
 ']',
 '.',
 'а',
 'в',
 '1896',
 'год',
 'американский',
 'астроном',
 'д',
 '.',
 'м',
 '.',
 'шеберль',
 'открывать',
 'процион',
 'B',
 ',',
 'подтвердить',
 'то',
 'самый',
 'и',
 'второй',
 'предсказание',
 'бессель',
 '.',
 'в',
 '1915',
 'год',
 'американский',
 'астроном',
 'уолтер',
 'сидней',
 'адамс',
 'измерять',
 'спектр',
 'сириус',
 'B',
 '.',
 'из',
 'измерение',
 'следовать',
 ',',
 'что',
 'его',
 'температура',
 'не',
 'низкий',
 ',',
 'чем',
 'у',
 'сириус',
 'A',
 '(',
 'по',
 'современный',
 'данные',
 ',',
 'температура',
 'поверхность',
 'сириус',
 'B',
 'составлять',
 '25',
 '000',
 'K',
 ',',
 'а',
 'сириус',
 'A',
 '—',
 '10',
 '000',
 'к',
 '),',
 'что',
 ',',
 'с',
 'учет',
 'он',
 'в',
 '10',
 '000',
 'раз',
 'меньший',
 ',',
 'чем',
 'у',
 'сириус',
 'A',
 ',',
 'светимость',
 'указывать',
 'на',
 'очень',
 'малый',
 'радиус',
 'и',
 ',',
 'соответственно',
 ',',
 'высокий',
 'плотность',
 '—',
 '106',
 'г',
 '/',
 'см3',
 '(',
 'плотность',
 'сириус',
 '~',
 '0',
 ',',
 '25',
 'г',
 '/',
 'см3',
 ',',
 'плотность',
 'солнце',
 '~',
 '1',
 ',',
 '4',
 'г',
 '/',
 'см3',
 ')',
 '.']

In [75]:
pymorphy_lemmas = []
for token in tokens:
        parsed = morph.parse(token)
        if parsed:
            pymorphy_lemmas.append(parsed[0].normal_form)
        else:
            pymorphy_lemmas.append(token)

In [77]:
pymorphy_lemmas

['второй',
 'и',
 'третий',
 'открытый',
 'белый',
 'карлик',
 'стать',
 'сириус',
 'b',
 'и',
 'процион',
 'b',
 '.',
 'в',
 '1844',
 'год',
 'директор',
 'кёнигсбергский',
 'обсерватория',
 'фридрих',
 'бессель',
 ',',
 'анализировать',
 'дать',
 'наблюдение',
 ',',
 'который',
 'вестись',
 'с',
 '1755',
 'год',
 ',',
 'обнаружить',
 ',',
 'что',
 'сириус',
 ',',
 'яркий',
 'звезда',
 'земной',
 'небо',
 ',',
 'и',
 'процион',
 'периодически',
 ',',
 'хотя',
 'и',
 'весьма',
 'слабо',
 ',',
 'отклоняться',
 'от',
 'прямолинейный',
 'траектория',
 'движение',
 'по',
 'небесный',
 'сфера',
 '[',
 '5',
 ']',
 '.',
 'бессель',
 'прийти',
 'к',
 'вывод',
 ',',
 'что',
 'у',
 'каждый',
 'из',
 'они',
 'должный',
 'быть',
 'близкий',
 'спутник',
 '.',
 'сообщение',
 'быть',
 'встретить',
 'скептически',
 ',',
 'поскольку',
 'слабый',
 'спутник',
 'оставаться',
 'ненаблюдаемый',
 ',',
 'а',
 'он',
 'масса',
 'должный',
 'быть',
 'быть',
 'достаточно',
 'большой',
 '—',
 'сравнимый',
 'с',
 'масса',
 'сириус',
 'и',
 'процион',
 ',',
 'соответственно',
 '.',
 'в',
 'январь',
 '1862',
 'год',
 'элвин',
 'грэхэма',
 'кларк',
 ',',
 'юстировать',
 '18',
 '-',
 'дюймовый',
 'рефрактор',
 ',',
 'самый',
 'большой',
 'на',
 'то',
 'время',
 'телескоп',
 'в',
 'мир',
 '(',
 'dearborn',
 'telescope',
 '),',
 'впоследствии',
 'поставить',
 'семейный',
 'фирма',
 'кларк',
 'в',
 'обсерватория',
 'чикагский',
 'университет',
 ',',
 'обнаружить',
 'в',
 'непосредственный',
 'близость',
 'от',
 'сириус',
 'тусклый',
 'звёздочка',
 '.',
 'это',
 'быть',
 'спутник',
 'сириус',
 ',',
 'сириус',
 'b',
 ',',
 'предсказать',
 'бессель',
 '[',
 '6',
 ']',
 '.',
 'а',
 'в',
 '1896',
 'год',
 'американский',
 'астроном',
 'далее',
 '.',
 'м',
 '.',
 'шеберл',
 'открыть',
 'процион',
 'b',
 ',',
 'подтвердить',
 'тем',
 'самый',
 'и',
 'второе',
 'предсказание',
 'бессель',
 '.',
 'в',
 '1915',
 'год',
 'американский',
 'астроном',
 'уолтер',
 'сидней',
 'адамс',
 'измерить',
 'спектр',
 'сириус',
 'b',
 '.',
 'из',
 'измерение',
 'следовать',
 ',',
 'что',
 'он',
 'температура',
 'не',
 'ниже',
 ',',
 'чем',
 'у',
 'сириус',
 'a',
 '(',
 'по',
 'современный',
 'данные',
 ',',
 'температура',
 'поверхность',
 'сириус',
 'b',
 'составлять',
 '25',
 '000',
 'k',
 ',',
 'а',
 'сириус',
 'a',
 '—',
 '10',
 '000',
 'к',
 '),',
 'что',
 ',',
 'с',
 'учёт',
 'он',
 'в',
 '10',
 '000',
 'раз',
 'малый',
 ',',
 'чем',
 'у',
 'сириус',
 'a',
 ',',
 'светимость',
 'указывать',
 'на',
 'очень',
 'малый',
 'радиус',
 'и',
 ',',
 'соответственно',
 ',',
 'высокий',
 'плотность',
 '—',
 '106',
 'г',
 '/',
 'см3',
 '(',
 'плотность',
 'сириус',
 '~',
 '0',
 ',',
 '25',
 'г',
 '/',
 'см3',
 ',',
 'плотность',
 'солнце',
 '~',
 '1',
 ',',
 '4',
 'г',
 '/',
 'см3',
 ')',
 '.']

In [79]:
df = pd.DataFrame({
    'position': range(len(tokens)),
    'token': tokens,
    'mystem_lemma': mystem_lemmas,
    'pymorphy_lemma': pymorphy_lemmas
})

# Добавляем столбец с сравнением
df['is_same'] = df['mystem_lemma'] == df['pymorphy_lemma']
df['difference_type'] = df.apply(
    lambda row: 'разные_леммы' if not row['is_same'] else 'совпадают', 
    axis=1
)

In [86]:
different_df = df[~df['is_same']]

In [87]:
different_df

,position,token,mystem_lemma,pymorphy_lemma,is_same,difference_type
6,6,стали,становиться,стать,False,разные_леммы
8,8,B,B,b,False,разные_леммы
11,11,B,B,b,False,разные_леммы
17,17,Кёнигсбергской,кенигсбергский,кёнигсбергский,False,разные_леммы
23,23,данные,данные,дать,False,разные_леммы
32,32,обнаружил,обнаруживать,обнаружить,False,разные_леммы
64,64,пришёл,приходить,прийти,False,разные_леммы
80,80,встречено,встречать,встретить,False,разные_леммы
90,90,его,его,он,False,разные_леммы
112,112,Грэхэм,грэхэм,грэхэма,False,разные_леммы
130,130,Dearborn,Dearborn,dearborn,False,разные_леммы
131,131,Telescope,Telescope,telescope,False,разные_леммы
134,134,поставленный,поставлять,поставить,False,разные_леммы
143,143,обнаружил,обнаруживать,обнаружить,False,разные_леммы
150,150,звёздочку,звездочка,звёздочка,False,разные_леммы
158,158,B,B,b,False,разные_леммы
160,160,предсказанный,предсказывать,предсказать,False,разные_леммы
172,172,Д,д,далее,False,разные_леммы
176,176,Шеберле,шеберль,шеберл,False,разные_леммы
177,177,открыл,открывать,открыть,False,разные_леммы
179,179,B,B,b,False,разные_леммы
182,182,тем,то,тем,False,разные_леммы
185,185,второе,второй,второе,False,разные_леммы
197,197,измерил,измерять,измерить,False,разные_леммы
200,200,B,B,b,False,разные_леммы
207,207,его,его,он,False,разные_леммы
210,210,ниже,низкий,ниже,False,разные_леммы
215,215,A,A,a,False,разные_леммы
224,224,B,B,b,False,разные_леммы
228,228,K,K,k,False,разные_леммы
232,232,A,A,a,False,разные_леммы
241,241,учётом,учет,учёт,False,разные_леммы
247,247,меньшей,меньший,малый,False,разные_леммы
252,252,A,A,a,False,разные_леммы

### Оба лемматизатора делают различные типы ошибок, но, на мой взляд, чуть лучше справился mystem, за счет правильного выбота в случаее неодносзначность слова например - "данные".

## 4. Лемматизация в SpaCy (2 балла)

С помощью Spacy (модель для русского языка) лемматизируйте тот же текст. Проверьте есть ли различия с Mystem и Pymoprhy.

In [88]:

import spacy
nlp = spacy.load("ru_core_news_sm")

In [89]:
# Лемматизация spaCy на тех же токенах из Mystem
spacy_lemmas = []
for token in tokens:
    doc = nlp(token)
    if len(doc) > 0:
        spacy_lemmas.append(doc[0].lemma_)
    else:
        spacy_lemmas.append(token)

In [90]:
df['spacy_lemma'] = spacy_lemmas
df['mystem_vs_spacy'] = df['mystem_lemma'] == df['spacy_lemma']
df['pymorphy_vs_spacy'] = df['pymorphy_lemma'] == df['spacy_lemma']
df['all_three_same'] = df['is_same'] & df['mystem_vs_spacy'] & df['pymorphy_vs_spacy']

In [91]:
df

,position,token,mystem_lemma,pymorphy_lemma,is_same,difference_type,spacy_lemma,mystem_vs_spacy,pymorphy_vs_spacy,all_three_same
0,0,Вторым,второй,второй,True,совпадают,второй,True,True,True
1,1,и,и,и,True,совпадают,и,True,True,True
2,2,третьим,третий,третий,True,совпадают,третий,True,True,True
3,3,открытыми,открытый,открытый,True,совпадают,открытый,True,True,True
4,4,белыми,белый,белый,True,совпадают,белый,True,True,True
5,5,карликами,карлик,карлик,True,совпадают,карлик,True,True,True
6,6,стали,становиться,стать,False,разные_леммы,стать,False,True,False
7,7,Сириус,сириус,сириус,True,совпадают,сириус,True,True,True
8,8,B,B,b,False,разные_леммы,b,False,True,False
9,9,и,и,и,True,совпадают,и,True,True,True
10,10,Процион,процион,процион,True,совпадают,процион,True,True,True
11,11,B,B,b,False,разные_леммы,b,False,True,False
12,12,.,.,.,True,совпадают,.,True,True,True
13,13,В,в,в,True,совпадают,в,True,True,True
14,14,1844,1844,1844,True,совпадают,1844,True,True,True
15,15,году,год,год,True,совпадают,год,True,True,True
16,16,директор,директор,директор,True,совпадают,директор,True,True,True
17,17,Кёнигсбергской,кенигсбергский,кёнигсбергский,False,разные_леммы,кёнигсбергский,False,True,False
18,18,обсерватории,обсерватория,обсерватория,True,совпадают,обсерватория,True,True,True
19,19,Фридрих,фридрих,фридрих,True,совпадают,фридрих,True,True,True
20,20,Бессель,бессель,бессель,True,совпадают,бессель,True,True,True
21,21,",",",",",",True,совпадают,",",True,True,True
22,22,анализируя,анализировать,анализировать,True,совпадают,анализировать,True,True,True
23,23,данные,данные,дать,False,разные_леммы,данные,True,False,False
24,24,наблюдений,наблюдение,наблюдение,True,совпадают,наблюдение,True,True,True
25,25,",",",",",",True,совпадают,",",True,True,True
26,26,которые,который,который,True,совпадают,которые,False,False,False
27,27,велись,вестись,вестись,True,совпадают,вестись,True,True,True
28,28,с,с,с,True,совпадают,с,True,True,True
29,29,1755,1755,1755,True,совпадают,1755,True,True,True
30,30,года,год,год,True,совпадают,год,True,True,True
31,31,",",",",",",True,совпадают,",",True,True,True
32,32,обнаружил,обнаруживать,обнаружить,False,разные_леммы,обнаружить,False,True,False
33,33,",",",",",",True,совпадают,",",True,True,True
34,34,что,что,что,True,совпадают,что,True,True,True
35,35,Сириус,сириус,сириус,True,совпадают,сириус,True,True,True
36,36,",",",",",",True,совпадают,",",True,True,True
37,37,ярчайшая,яркий,яркий,True,совпадают,ярчайшая,False,False,False
38,38,звезда,звезда,звезда,True,совпадают,звезда,True,True,True
39,39,земного,земной,земной,True,совпадают,земной,True,True,True
40,40,неба,небо,небо,True,совпадают,небо,True,True,True
41,41,",",",",",",True,совпадают,",",True,True,True
42,42,и,и,и,True,совпадают,и,True,True,True
43,43,Процион,процион,процион,True,совпадают,процион,True,True,True
44,44,периодически,периодически,периодически,True,совпадают,периодически,True,True,True
45,45,",",",",",",True,совпадают,",",True,True,True
46,46,хотя,хотя,хотя,True,совпадают,хотя,True,True,True
47,47,и,и,и,True,совпадают,и,True,True,True
48,48,весьма,весьма,весьма,True,совпадают,весьма,True,True,True
49,49,слабо,слабо,слабо,True,совпадают,слабо,True,True,True
50,50,",",",",",",True,совпадают,",",True,True,True
51,51,отклоняются,отклоняться,отклоняться,True,совпадают,отклоняться,True,True,True
52,52,от,от,от,True,совпадают,от,True,True,True
53,53,прямолинейной,прямолинейный,прямолинейный,True,совпадают,прямолинейный,True,True,True
54,54,траектории,траектория,траектория,True,совпадают,траектория,True,True,True
55,55,движения,движение,движение,True,совпадают,движение,True,True,True
56,56,по,по,по,True,совпадают,по,True,True,True
57,57,небесной,небесный,небесный,True,совпадают,небесный,True,True,True
58,58,сфере,сфера,сфера,True,совпадают,сфера,True,True,True
59,59,[,[,[,True,совпадают,[,True,True,True
60,60,5,5,5,True,совпадают,5,True,True,True
61,61,],],],True,совпадают,],True,True,True
62,62,.,.,.,True,совпадают,.,True,True,True
63,63,Бессель,бессель,бессель,True,совпадают,бессель,True,True,True
64,64,пришёл,приходить,прийти,False,разные_леммы,прийти,False,True,False
65,65,к,к,к,True,совпадают,к,True,True,True
66,66,выводу,вывод,вывод,True,совпадают,вывод,True,True,True
67,67,",",",",",",True,совпадают,",",True,True,True
68,68,что,что,что,True,совпадают,что,True,True,True
69,69,у,у,у,True,совпадают,у,True,True,True
70,70,каждой,каждый,каждый,True,совпадают,каждый,True,True,True
71,71,из,из,из,True,совпадают,из,True,True,True
72,72,них,они,они,True,совпадают,них,False,False,False
73,73,должен,должный,должный,True,совпадают,должный,True,True,True
74,74,быть,быть,быть,True,совпадают,быть,True,True,True
75,75,близкий,близкий,близкий,True,совпадают,близкий,True,True,True
76,76,спутник,спутник,спутник,True,совпадают,спутник,True,True,True
77,77,.,.,.,True,совпадают,.,True,True,True
78,78,Сообщение,сообщение,сообщение,True,совпадают,сообщение,True,True,True
79,79,было,быть,быть,True,совпадают,было,False,False,False
80,80,встречено,встречать,встретить,False,разные_леммы,встретить,False,True,False
81,81,скептически,скептически,скептически,True,совпадают,скептически,True,True,True
82,82,",",",",",",True,совпадают,",",True,True,True
83,83,поскольку,поскольку,поскольку,True,совпадают,поскольку,True,True,True
84,84,слабый,слабый,слабый,True,совпадают,слабый,True,True,True
85,85,спутник,спутник,спутник,True,совпадают,спутник,True,True,True
86,86,оставался,оставаться,оставаться,True,совпадают,оставаться,True,True,True
87,87,ненаблюдаемым,ненаблюдаемый,ненаблюдаемый,True,совпадают,ненаблюдаемый,True,True,True
88,88,",",",",",",True,совпадают,",",True,True,True
89,89,а,а,а,True,совпадают,а,True,True,True
90,90,его,его,он,False,разные_леммы,его,True,False,False
91,91,масса,масса,масса,True,совпадают,масса,True,True,True
92,92,должна,должный,должный,True,совпадают,должный,True,True,True
93,93,была,быть,быть,True,совпадают,быть,True,True,True
94,94,быть,быть,быть,True,совпадают,быть,True,True,True
95,95,достаточно,достаточно,достаточно,True,совпадают,достаточный,False,False,False
96,96,велика,большой,большой,True,совпадают,большой,True,True,True
97,97,—,—,—,True,совпадают,—,True,True,True
98,98,сравнимой,сравнимый,сравнимый,True,совпадают,сравнимой,False,False,False
99,99,с,с,с,True,совпадают,с,True,True,True
100,100,массой,масса,масса,True,совпадают,масса,True,True,True
101,101,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
102,102,и,и,и,True,совпадают,и,True,True,True
103,103,Проциона,процион,процион,True,совпадают,проциона,False,False,False
104,104,",",",",",",True,совпадают,",",True,True,True
105,105,соответственно,соответственно,соответственно,True,совпадают,соответственно,True,True,True
106,106,.,.,.,True,совпадают,.,True,True,True
107,107,В,в,в,True,совпадают,в,True,True,True
108,108,январе,январь,январь,True,совпадают,январь,True,True,True
109,109,1862,1862,1862,True,совпадают,1862,True,True,True
110,110,года,год,год,True,совпадают,год,True,True,True
111,111,Элвин,элвин,элвин,True,совпадают,элвин,True,True,True
112,112,Грэхэм,грэхэм,грэхэма,False,разные_леммы,грэхэм,True,False,False
113,113,Кларк,кларк,кларк,True,совпадают,кларк,True,True,True
114,114,",",",",",",True,совпадают,",",True,True,True
115,115,юстируя,юстировать,юстировать,True,совпадают,юстировать,True,True,True
116,116,18,18,18,True,совпадают,18,True,True,True
117,117,-,-,-,True,совпадают,-,True,True,True
118,118,дюймовый,дюймовый,дюймовый,True,совпадают,дюймовый,True,True,True
119,119,рефрактор,рефрактор,рефрактор,True,совпадают,рефрактор,True,True,True
120,120,",",",",",",True,совпадают,",",True,True,True
121,121,самый,самый,самый,True,совпадают,самый,True,True,True
122,122,большой,большой,большой,True,совпадают,большой,True,True,True
123,123,на,на,на,True,совпадают,на,True,True,True
124,124,то,то,то,True,совпадают,то,True,True,True
125,125,время,время,время,True,совпадают,время,True,True,True
126,126,телескоп,телескоп,телескоп,True,совпадают,телескоп,True,True,True
127,127,в,в,в,True,совпадают,в,True,True,True
128,128,мире,мир,мир,True,совпадают,мир,True,True,True
129,129,(,(,(,True,совпадают,(,True,True,True
130,130,Dearborn,Dearborn,dearborn,False,разные_леммы,dearborn,False,True,False
131,131,Telescope,Telescope,telescope,False,разные_леммы,telescope,False,True,False
132,132,"),","),","),",True,совпадают,),False,False,False
133,133,впоследствии,впоследствии,впоследствии,True,совпадают,впоследствии,True,True,True
134,134,поставленный,поставлять,поставить,False,разные_леммы,поставить,False,True,False
135,135,семейной,семейный,семейный,True,совпадают,семейный,True,True,True
136,136,фирмой,фирма,фирма,True,совпадают,фирма,True,True,True
137,137,Кларков,кларк,кларк,True,совпадают,кларков,False,False,False
138,138,в,в,в,True,совпадают,в,True,True,True
139,139,обсерваторию,обсерватория,обсерватория,True,совпадают,обсерватория,True,True,True
140,140,Чикагского,чикагский,чикагский,True,совпадают,чикагского,False,False,False
141,141,университета,университет,университет,True,совпадают,университет,True,True,True
142,142,",",",",",",True,совпадают,",",True,True,True
143,143,обнаружил,обнаруживать,обнаружить,False,разные_леммы,обнаружить,False,True,False
144,144,в,в,в,True,совпадают,в,True,True,True
145,145,непосредственной,непосредственный,непосредственный,True,совпадают,непосредственный,True,True,True
146,146,близости,близость,близость,True,совпадают,близость,True,True,True
147,147,от,от,от,True,совпадают,от,True,True,True
148,148,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
149,149,тусклую,тусклый,тусклый,True,совпадают,тусклый,True,True,True
150,150,звёздочку,звездочка,звёздочка,False,разные_леммы,звёздочка,False,True,False
151,151,.,.,.,True,совпадают,.,True,True,True
152,152,Это,это,это,True,совпадают,это,True,True,True
153,153,был,быть,быть,True,совпадают,быть,True,True,True
154,154,спутник,спутник,спутник,True,совпадают,спутник,True,True,True
155,155,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
156,156,",",",",",",True,совпадают,",",True,True,True
157,157,Сириус,сириус,сириус,True,совпадают,сириус,True,True,True
158,158,B,B,b,False,разные_леммы,b,False,True,False
159,159,",",",",",",True,совпадают,",",True,True,True
160,160,предсказанный,предсказывать,предсказать,False,разные_леммы,предсказанный,False,False,False
161,161,Бесселем,бессель,бессель,True,совпадают,бесселем,False,False,False
162,162,[,[,[,True,совпадают,[,True,True,True
163,163,6,6,6,True,совпадают,6,True,True,True
164,164,],],],True,совпадают,],True,True,True
165,165,.,.,.,True,совпадают,.,True,True,True
166,166,А,а,а,True,совпадают,а,True,True,True
167,167,в,в,в,True,совпадают,в,True,True,True
168,168,1896,1896,1896,True,совпадают,1896,True,True,True
169,169,году,год,год,True,совпадают,год,True,True,True
170,170,американский,американский,американский,True,совпадают,американский,True,True,True
171,171,астроном,астроном,астроном,True,совпадают,астрон,False,False,False
172,172,Д,д,далее,False,разные_леммы,Д,False,False,False
173,173,.,.,.,True,совпадают,.,True,True,True
174,174,М,м,м,True,совпадают,м,True,True,True
175,175,.,.,.,True,совпадают,.,True,True,True
176,176,Шеберле,шеберль,шеберл,False,разные_леммы,шеберле,False,False,False
177,177,открыл,открывать,открыть,False,разные_леммы,открыть,False,True,False
178,178,Процион,процион,процион,True,совпадают,процион,True,True,True
179,179,B,B,b,False,разные_леммы,b,False,True,False
180,180,",",",",",",True,совпадают,",",True,True,True
181,181,подтвердив,подтвердить,подтвердить,True,совпадают,подтвердить,True,True,True
182,182,тем,то,тем,False,разные_леммы,тем,False,True,False
183,183,самым,самый,самый,True,совпадают,самым,False,False,False
184,184,и,и,и,True,совпадают,и,True,True,True
185,185,второе,второй,второе,False,разные_леммы,второй,True,False,False
186,186,предсказание,предсказание,предсказание,True,совпадают,предсказание,True,True,True
187,187,Бесселя,бессель,бессель,True,совпадают,бесселя,False,False,False
188,188,.,.,.,True,совпадают,.,True,True,True
189,189,В,в,в,True,совпадают,в,True,True,True
190,190,1915,1915,1915,True,совпадают,1915,True,True,True
191,191,году,год,год,True,совпадают,год,True,True,True
192,192,американский,американский,американский,True,совпадают,американский,True,True,True
193,193,астроном,астроном,астроном,True,совпадают,астрон,False,False,False
194,194,Уолтер,уолтер,уолтер,True,совпадают,уолтер,True,True,True
195,195,Сидней,сидней,сидней,True,совпадают,сидней,True,True,True
196,196,Адамс,адамс,адамс,True,совпадают,адамс,True,True,True
197,197,измерил,измерять,измерить,False,разные_леммы,измерить,False,True,False
198,198,спектр,спектр,спектр,True,совпадают,спектр,True,True,True
199,199,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
200,200,B,B,b,False,разные_леммы,b,False,True,False
201,201,.,.,.,True,совпадают,.,True,True,True
202,202,Из,из,из,True,совпадают,Из,False,False,False
203,203,измерений,измерение,измерение,True,совпадают,измерение,True,True,True
204,204,следовало,следовать,следовать,True,совпадают,следовать,True,True,True
205,205,",",",",",",True,совпадают,",",True,True,True
206,206,что,что,что,True,совпадают,что,True,True,True
207,207,его,его,он,False,разные_леммы,его,True,False,False
208,208,температура,температура,температура,True,совпадают,температура,True,True,True
209,209,не,не,не,True,совпадают,не,True,True,True
210,210,ниже,низкий,ниже,False,разные_леммы,низкий,True,False,False
211,211,",",",",",",True,совпадают,",",True,True,True
212,212,чем,чем,чем,True,совпадают,чем,True,True,True
213,213,у,у,у,True,совпадают,у,True,True,True
214,214,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
215,215,A,A,a,False,разные_леммы,a,False,True,False
216,216,(,(,(,True,совпадают,(,True,True,True
217,217,по,по,по,True,совпадают,по,True,True,True
218,218,современным,современный,современный,True,совпадают,современный,True,True,True
219,219,данным,данные,данные,True,совпадают,данным,False,False,False
220,220,",",",",",",True,совпадают,",",True,True,True
221,221,температура,температура,температура,True,совпадают,температура,True,True,True
222,222,поверхности,поверхность,поверхность,True,совпадают,поверхность,True,True,True
223,223,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
224,224,B,B,b,False,разные_леммы,b,False,True,False
225,225,составляет,составлять,составлять,True,совпадают,составлять,True,True,True
226,226,25,25,25,True,совпадают,25,True,True,True
227,227,000,000,000,True,совпадают,000,True,True,True
228,228,K,K,k,False,разные_леммы,k,False,True,False
229,229,",",",",",",True,совпадают,",",True,True,True
230,230,а,а,а,True,совпадают,а,True,True,True
231,231,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
232,232,A,A,a,False,разные_леммы,a,False,True,False
233,233,—,—,—,True,совпадают,—,True,True,True
234,234,10,10,10,True,совпадают,10,True,True,True
235,235,000,000,000,True,совпадают,000,True,True,True
236,236,К,к,к,True,совпадают,К,False,False,False
237,237,"),","),","),",True,совпадают,),False,False,False
238,238,что,что,что,True,совпадают,что,True,True,True
239,239,",",",",",",True,совпадают,",",True,True,True
240,240,с,с,с,True,совпадают,с,True,True,True
241,241,учётом,учет,учёт,False,разные_леммы,учёт,False,True,False
242,242,его,он,он,True,совпадают,его,False,False,False
243,243,в,в,в,True,совпадают,в,True,True,True
244,244,10,10,10,True,совпадают,10,True,True,True
245,245,000,000,000,True,совпадают,000,True,True,True
246,246,раз,раз,раз,True,совпадают,раз,True,True,True
247,247,меньшей,меньший,малый,False,разные_леммы,малый,False,True,False
248,248,",",",",",",True,совпадают,",",True,True,True
249,249,чем,чем,чем,True,совпадают,чем,True,True,True
250,250,у,у,у,True,совпадают,у,True,True,True
251,251,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
252,252,A,A,a,False,разные_леммы,a,False,True,False
253,253,",",",",",",True,совпадают,",",True,True,True
254,254,светимости,светимость,светимость,True,совпадают,светимость,True,True,True
255,255,указывает,указывать,указывать,True,совпадают,указывать,True,True,True
256,256,на,на,на,True,совпадают,на,True,True,True
257,257,очень,очень,очень,True,совпадают,очень,True,True,True
258,258,малый,малый,малый,True,совпадают,малый,True,True,True
259,259,радиус,радиус,радиус,True,совпадают,радиус,True,True,True
260,260,и,и,и,True,совпадают,и,True,True,True
261,261,",",",",",",True,совпадают,",",True,True,True
262,262,соответственно,соответственно,соответственно,True,совпадают,соответственно,True,True,True
263,263,",",",",",",True,совпадают,",",True,True,True
264,264,высокую,высокий,высокий,True,совпадают,высокий,True,True,True
265,265,плотность,плотность,плотность,True,совпадают,плотность,True,True,True
266,266,—,—,—,True,совпадают,—,True,True,True
267,267,106,106,106,True,совпадают,106,True,True,True
268,268,г,г,г,True,совпадают,г,True,True,True
269,269,/,/,/,True,совпадают,/,True,True,True
270,270,см3,см3,см3,True,совпадают,см3,True,True,True
271,271,(,(,(,True,совпадают,(,True,True,True
272,272,плотность,плотность,плотность,True,совпадают,плотность,True,True,True
273,273,Сириуса,сириус,сириус,True,совпадают,сириус,True,True,True
274,274,~,~,~,True,совпадают,~,True,True,True
275,275,0,0,0,True,совпадают,0,True,True,True
276,276,",",",",",",True,совпадают,",",True,True,True
277,277,25,25,25,True,совпадают,25,True,True,True
278,278,г,г,г,True,совпадают,г,True,True,True
279,279,/,/,/,True,совпадают,/,True,True,True
280,280,см3,см3,см3,True,совпадают,см3,True,True,True
281,281,",",",",",",True,совпадают,",",True,True,True
282,282,плотность,плотность,плотность,True,совпадают,плотность,True,True,True
283,283,Солнца,солнце,солнце,True,совпадают,солнце,True,True,True
284,284,~,~,~,True,совпадают,~,True,True,True
285,285,1,1,1,True,совпадают,1,True,True,True
286,286,",",",",",",True,совпадают,",",True,True,True
287,287,4,4,4,True,совпадают,4,True,True,True
288,288,г,г,г,True,совпадают,г,True,True,True
289,289,/,/,/,True,совпадают,/,True,True,True
290,290,см3,см3,см3,True,совпадают,см3,True,True,True
291,291,),),),True,совпадают,),True,True,True
292,292,.,.,.,True,совпадают,.,True,True,True

In [92]:
different_all_df = df[~df['all_three_same']]

In [93]:
different_all_df

,position,token,mystem_lemma,pymorphy_lemma,is_same,difference_type,spacy_lemma,mystem_vs_spacy,pymorphy_vs_spacy,all_three_same
6,6,стали,становиться,стать,False,разные_леммы,стать,False,True,False
8,8,B,B,b,False,разные_леммы,b,False,True,False
11,11,B,B,b,False,разные_леммы,b,False,True,False
17,17,Кёнигсбергской,кенигсбергский,кёнигсбергский,False,разные_леммы,кёнигсбергский,False,True,False
23,23,данные,данные,дать,False,разные_леммы,данные,True,False,False
26,26,которые,который,который,True,совпадают,которые,False,False,False
32,32,обнаружил,обнаруживать,обнаружить,False,разные_леммы,обнаружить,False,True,False
37,37,ярчайшая,яркий,яркий,True,совпадают,ярчайшая,False,False,False
64,64,пришёл,приходить,прийти,False,разные_леммы,прийти,False,True,False
72,72,них,они,они,True,совпадают,них,False,False,False
79,79,было,быть,быть,True,совпадают,было,False,False,False
80,80,встречено,встречать,встретить,False,разные_леммы,встретить,False,True,False
90,90,его,его,он,False,разные_леммы,его,True,False,False
95,95,достаточно,достаточно,достаточно,True,совпадают,достаточный,False,False,False
98,98,сравнимой,сравнимый,сравнимый,True,совпадают,сравнимой,False,False,False
103,103,Проциона,процион,процион,True,совпадают,проциона,False,False,False
112,112,Грэхэм,грэхэм,грэхэма,False,разные_леммы,грэхэм,True,False,False
130,130,Dearborn,Dearborn,dearborn,False,разные_леммы,dearborn,False,True,False
131,131,Telescope,Telescope,telescope,False,разные_леммы,telescope,False,True,False
132,132,"),","),","),",True,совпадают,),False,False,False
134,134,поставленный,поставлять,поставить,False,разные_леммы,поставить,False,True,False
137,137,Кларков,кларк,кларк,True,совпадают,кларков,False,False,False
140,140,Чикагского,чикагский,чикагский,True,совпадают,чикагского,False,False,False
143,143,обнаружил,обнаруживать,обнаружить,False,разные_леммы,обнаружить,False,True,False
150,150,звёздочку,звездочка,звёздочка,False,разные_леммы,звёздочка,False,True,False
158,158,B,B,b,False,разные_леммы,b,False,True,False
160,160,предсказанный,предсказывать,предсказать,False,разные_леммы,предсказанный,False,False,False
161,161,Бесселем,бессель,бессель,True,совпадают,бесселем,False,False,False
171,171,астроном,астроном,астроном,True,совпадают,астрон,False,False,False
172,172,Д,д,далее,False,разные_леммы,Д,False,False,False
176,176,Шеберле,шеберль,шеберл,False,разные_леммы,шеберле,False,False,False
177,177,открыл,открывать,открыть,False,разные_леммы,открыть,False,True,False
179,179,B,B,b,False,разные_леммы,b,False,True,False
182,182,тем,то,тем,False,разные_леммы,тем,False,True,False
183,183,самым,самый,самый,True,совпадают,самым,False,False,False
185,185,второе,второй,второе,False,разные_леммы,второй,True,False,False
187,187,Бесселя,бессель,бессель,True,совпадают,бесселя,False,False,False
193,193,астроном,астроном,астроном,True,совпадают,астрон,False,False,False
197,197,измерил,измерять,измерить,False,разные_леммы,измерить,False,True,False
200,200,B,B,b,False,разные_леммы,b,False,True,False
202,202,Из,из,из,True,совпадают,Из,False,False,False
207,207,его,его,он,False,разные_леммы,его,True,False,False
210,210,ниже,низкий,ниже,False,разные_леммы,низкий,True,False,False
215,215,A,A,a,False,разные_леммы,a,False,True,False
219,219,данным,данные,данные,True,совпадают,данным,False,False,False
224,224,B,B,b,False,разные_леммы,b,False,True,False
228,228,K,K,k,False,разные_леммы,k,False,True,False
232,232,A,A,a,False,разные_леммы,a,False,True,False
236,236,К,к,к,True,совпадают,К,False,False,False
237,237,"),","),","),",True,совпадают,),False,False,False
241,241,учётом,учет,учёт,False,разные_леммы,учёт,False,True,False
242,242,его,он,он,True,совпадают,его,False,False,False
247,247,меньшей,меньший,малый,False,разные_леммы,малый,False,True,False
252,252,A,A,a,False,разные_леммы,a,False,True,False

In [94]:
print(f"Токены, где все три лемматизатора совпадают: {len(df[df['all_three_same']])}")
print(f"Токены с различиями: {len(different_all_df)}")
print(f"Совпадение Mystem и Pymorphy: {len(df[df['is_same']])} ({len(df[df['is_same']])/len(df)*100:.1f}%)")
print(f"Совпадение Mystem и spaCy: {len(df[df['mystem_vs_spacy']])} ({len(df[df['mystem_vs_spacy']])/len(df)*100:.1f}%)")
print(f"Совпадение Pymorphy и spaCy: {len(df[df['pymorphy_vs_spacy']])} ({len(df[df['pymorphy_vs_spacy']])/len(df)*100:.1f}%)")

Токены, где все три лемматизатора совпадают: 239
Токены с различиями: 54
Совпадение Mystem и Pymorphy: 259 (88.4%)
Совпадение Mystem и spaCy: 245 (83.6%)
Совпадение Pymorphy и spaCy: 264 (90.1%)

### Ошибки сохраняются. spaCy правильно решает некоторые ошибки обоих лемматизаторов, однако создает свои (строчка 219)

## 5*. LSH (2 балла)

*необязательное задание чтобы получить 10 баллов

Попробуйте искать дубликаты в настоящих текстах. Например, можете взять https://github.com/mannefedov/compling_nlp_hse_course/blob/master/data/anna_karenina.txt или https://github.com/mannefedov/compling_nlp_hse_course/blob/master/data/besy_dostoevsky.txt (или любой другой корпус)

Используйте код из семинара для нахождения кандидатов в дубликаты (шинглы -> минхэш - lsh) и рассчитайте реальную меру Жаккара между полученными кандидатами. Настройте параметры k, num_hash_functions, bands так чтобы результаты получались адекватные (мера Жаккара хотя бы больше нуля). 

(Можете взять 500-1000 текстов если весь корпус обрабатывается слишком долго)

In [101]:
def get_shingles(text, k=5):
    """генерирует список шинглов из строки (символьные шинглы)"""
    shingles = set()
    for i in range(len(text) - k + 1):
        shingle = text[i:i + k]
        shingles.add(shingle)
    return shingles

In [102]:
import hashlib
def hash_string(s):
    """хеширует строку и возвращает число"""
    return int(hashlib.md5(s.encode('utf8')).hexdigest(), 16)

In [103]:
def generate_hash_functions(k):
    """генерирует k хеш-функций добавляя индекс к строке"""
    functions = []
    for i in range(k):
        functions.append(lambda x, i=i: hash_string(x + str(i)))
    return functions

In [ ]:
def compute_minhash_signature(shingles, hash_funcs):
    """вычисляет minhash-сигнатуру для списка шинглов"""
    signature = []
    for hash_func in hash_funcs:
        if not shingles:
            signature.append(2**128 - 1)
            continue
        min_hash = min(hash_func(shingle) for shingle in shingles)
        signature.append(min_hash)
    return signature

In [ ]:
def find_similar_strings(strings_list, k=5, num_hashes=100, bands=20):
    hash_funcs = generate_hash_functions(num_hashes)
    signatures = []
    shingles_list = []

    # каждый текст обрабатывается отдельно: шинглы и сигнатуры
    for string in tqdm(strings_list, desc="MinHash (chunks)"):
        shingles = get_shingles(string, k)
        shingles_list.append(shingles)
        signature = compute_minhash_signature(shingles, hash_funcs)
        signatures.append(signature)

    # вычисляются кандидаты по кускам сигнатур
    buckets = lsh(signatures, bands)
    candidates = set()
    for bucket_items in buckets.values():
        if len(bucket_items) > 1:
            for i in bucket_items:
                for j in bucket_items:
                    if i < j:
                        candidates.add((i, j))

    return candidates, signatures, shingles_list

In [ ]:
def get_jaccard(x, y, k=10):
    x_sh = get_shingles(x, k)
    y_sh = get_shingles(y, k)
    if not x_sh or not y_sh:
        return 0.0
    return len(x_sh & y_sh) / len(x_sh | y_sh)

In [ ]:
from lxml import etree

def extract_text_from_fb2(path: str) -> str:
    parser = etree.XMLParser(recover=True)
    tree = etree.parse(path, parser)
    root = tree.getroot()
    ns = {"fb": "http://www.gribuser.ru/xml/fictionbook/2.0"}
    ps = root.xpath('//fb:body//fb:p', namespaces=ns)
    return " ".join((p.text or "").strip() for p in ps if p.text)


def split_into_sliding_windows_words(text: str, window_size=200, step=200):
  
    words = text.split()
    if not words:
        return []
    chunks = []
    for start in range(0, max(1, len(words)-window_size+1), step):
        win = words[start:start+window_size]
        chunks.append(" ".join(win))
    if not chunks:
        chunks.append(" ".join(words))
    return chunks

In [ ]:
import itertools

def test_lsh(raw_text, param_combinations):
    
    all_results = []
    
    for params in param_combinations:
        print(f"\n{'='*80}")
        print(f"ТЕСТ: {params}")
        print(f"{'='*80}")
        
        windows = split_into_sliding_windows_words(
            raw_text, 
            window_size=params['window_size'],
            step=params['window_size']
        )
        
        print(f"Создано окон (без перекрытия): {len(windows)}")
        if len(windows) > 0:
            print(f"Пример окна: {windows[0][:100]}...")
        
        candidates, signatures, shingles_list = find_similar_strings(
            strings_list=windows,
            k=params['k'],
            num_hashes=params['num_hashes'],
            bands=params['bands']
        )
        
        print(f"Кандидатов найдено: {len(candidates)}")
        
        flat_pairs = set()
        if isinstance(candidates, set):
            for pair in candidates:
                if isinstance(pair, (list, tuple)) and len(pair) == 2:
                    flat_pairs.add(tuple(sorted(pair)))
        
        # Вычисляем Jaccard
        similar_pairs = []
        for pair in flat_pairs:
            i, j = pair
            if abs(i - j) > 1: 
                jac = get_jaccard(windows[i], windows[j])
                if jac > 0:
                    similar_pairs.append((i, j, jac))
        
        similar_pairs.sort(key=lambda x: -x[2])
        
        # Сохраняем результаты
        result = {
            'params': params,
            'windows_count': len(windows),
            'candidates_count': len(candidates),
            'similar_pairs_count': len(similar_pairs),
            'similar_pairs': similar_pairs[:10],  # Топ-10 пар
            'max_jaccard': similar_pairs[0][2] if similar_pairs else 0
        }
        
        all_results.append(result)
        
        # Выводим результаты
        print(f"Похожих пар (J>0): {len(similar_pairs)}")
        print(f"Максимальный Jaccard: {result['max_jaccard']:.4f}")
        
        if similar_pairs:
            print("Топ-5 похожих пар:")
            for i, j, jac in similar_pairs[:5]:
                print(f"  {i} — {j} | J={jac:.4f}")
                # Показываем пример для лучшей пары
                if jac == result['max_jaccard']:
                    print(f"    Окно {i}: {windows[i][:80]}...")
                    print(f"    Окно {j}: {windows[j][:80]}...")
        else:
            print("Похожих пар не найдено")
    
    return all_results

In [148]:
def analyze_all_results(all_results):
    
    successful_results = [r for r in all_results if r['similar_pairs_count'] > 0]
    
    if not successful_results:
        print("не найдено похожих пар")
        return
    print(f"Успешных экспериментов: {len(successful_results)} из {len(all_results)}")
    
    print("\nЛучгий результат (макс. jaccard):")
    successful_results.sort(key=lambda x: x['max_jaccard'], reverse=True)
    for i, result in enumerate(successful_results[:5]):
        p = result['params']
        print(f"{i+1}. J={result['max_jaccard']:.4f}")
        print(f"   Окна: {p['window_size']}, k={p['k']}, hashes={p['num_hashes']}, bands={p['bands']}")
        print(f"   Всего пар: {result['similar_pairs_count']}")
    
    print("\n лучший по количеству пар:")
    successful_results.sort(key=lambda x: x['similar_pairs_count'], reverse=True)
    for i, result in enumerate(successful_results[:3]):
        p = result['params']
        print(f"{i+1}. Пар: {result['similar_pairs_count']}")
        print(f"   Окна: {p['window_size']}, k={p['k']}, Макс.J: {result['max_jaccard']:.4f}")
    
    best_result = successful_results[0]
    print(f"\nлучший результат:")
    print(f"   Параметры: {best_result['params']}")
    print(f"   Макс. Jaccard: {best_result['max_jaccard']:.4f}")
    print(f"   Всего пар: {best_result['similar_pairs_count']}")
    
    if best_result['similar_pairs']:
        print(f"\n пары:")
        for i, j, jac in best_result['similar_pairs'][:3]:
            print(f"   Окна {i}-{j} | J={jac:.4f}")

In [147]:

raw_text = extract_text_from_fb2("/Users/kseniazavyalova/Downloads/Mayer_Sumerechnaya-saga_1_Sumerki.H4D0Fg.617935.fb2")
raw_text = raw_text.lower()

print(f"Длина текста: {len(raw_text)} символов")

Длина текста: 552075 символов

In [152]:
def lsh(signatures, bands):
    """Разрезает сигнатуры на куски (bands), и группирует индексы сигнатур по совпадению кусков"""
    buckets = defaultdict(list)
    band_length = len(signatures[0]) // bands
    
    for idx, sig in tqdm(enumerate(signatures)):
        for b in range(0, bands, band_length):
            start = b
            end = start + band_length
            band = tuple(sig[start:end])
            buckets[band].append(idx)
    return buckets

In [ ]:

param_combinations = [
    {'window_size': 50, 'k': 3, 'num_hashes': 100, 'bands': 25},
    {'window_size': 50, 'k': 4, 'num_hashes': 100, 'bands': 20},
    {'window_size': 50, 'k': 5, 'num_hashes': 100, 'bands': 10},
    {'window_size': 100, 'k': 3, 'num_hashes': 100, 'bands': 25},
    {'window_size': 100, 'k': 4, 'num_hashes': 100, 'bands': 20},
    {'window_size': 100, 'k': 5, 'num_hashes': 100, 'bands': 10},
    {'window_size': 200, 'k': 3, 'num_hashes': 150, 'bands': 30},
    {'window_size': 200, 'k': 4, 'num_hashes': 150, 'bands': 25},
    {'window_size': 200, 'k': 5, 'num_hashes': 150, 'bands': 15},
    {'window_size': 30, 'k': 2, 'num_hashes': 80, 'bands': 20},
    {'window_size': 30, 'k': 3, 'num_hashes': 80, 'bands': 16},
    {'window_size': 100, 'k': 4, 'num_hashes': 200, 'bands': 40},
    {'window_size': 100, 'k': 4, 'num_hashes': 50, 'bands': 10},
]

all_results = test_lsh(raw_text, param_combinations)

================================================================================
ТЕСТ: {'window_size': 50, 'k': 3, 'num_hashes': 100, 'bands': 25}
================================================================================
Создано окон (без перекрытия): 1808
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/1808 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 739
Похожих пар (J>0): 163
Максимальный Jaccard: 0.0351
Топ-5 похожих пар:
  328 — 402 | J=0.0351
    Окно 328: – пожалуй, да. я растерянно смотрела на свои руки, лихорадочно сжимающие лимонад...
    Окно 402: заиграла лукавая улыбка. – могу я кое о чем тебя попросить? – медовые с золотыми...
  182 — 301 | J=0.0293
  383 — 1576 | J=0.0282
  650 — 1345 | J=0.0265
  254 — 1093 | J=0.0251

================================================================================
ТЕСТ: {'window_size': 50, 'k': 4, 'num_hashes': 100, 'bands': 20}
================================================================================
Создано окон (без перекрытия): 1808
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/1808 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 0
Похожих пар (J>0): 0
Максимальный Jaccard: 0.0000
Похожих пар не найдено

================================================================================
ТЕСТ: {'window_size': 50, 'k': 5, 'num_hashes': 100, 'bands': 10}
================================================================================
Создано окон (без перекрытия): 1808
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/1808 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 0
Похожих пар (J>0): 0
Максимальный Jaccard: 0.0000
Похожих пар не найдено

================================================================================
ТЕСТ: {'window_size': 100, 'k': 3, 'num_hashes': 100, 'bands': 25}
================================================================================
Создано окон (без перекрытия): 904
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/904 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 880
Похожих пар (J>0): 413
Максимальный Jaccard: 0.0204
Топ-5 похожих пар:
  222 — 796 | J=0.0204
    Окно 222: с нами не поехали. почему их никто не пригласил? – на красивом лице отобразилось...
    Окно 796: поэтому имел два входа. абсурд, но однажды я чуть не заблудилась! едва за мной з...
  87 — 551 | J=0.0157
  0 — 521 | J=0.0147
  325 — 672 | J=0.0141
  444 — 600 | J=0.0134

================================================================================
ТЕСТ: {'window_size': 100, 'k': 4, 'num_hashes': 100, 'bands': 20}
================================================================================
Создано окон (без перекрытия): 904
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/904 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 4
Похожих пар (J>0): 4
Максимальный Jaccard: 0.0127
Топ-5 похожих пар:
  256 — 445 | J=0.0127
    Окно 256: без всяких мучений. странно, даже страшно! вторая половина дня оказалась весьма ...
    Окно 445: горечью продолжал эдвард. – мы ведь не прячемся, и если наши отношения зайдут сл...
  140 — 879 | J=0.0080
  321 — 445 | J=0.0026
  256 — 321 | J=0.0024

================================================================================
ТЕСТ: {'window_size': 100, 'k': 5, 'num_hashes': 100, 'bands': 10}
================================================================================
Создано окон (без перекрытия): 904
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/904 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 0
Похожих пар (J>0): 0
Максимальный Jaccard: 0.0000
Похожих пар не найдено

================================================================================
ТЕСТ: {'window_size': 200, 'k': 3, 'num_hashes': 150, 'bands': 30}
================================================================================
Создано окон (без перекрытия): 452
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/452 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 132
Похожих пар (J>0): 117
Максимальный Jaccard: 0.0156
Топ-5 похожих пар:
  219 — 277 | J=0.0156
    Окно 219: – как спала? – поинтересовался эдвард, и я еще раз восхитилась мелодичностью его...
    Окно 277: – хочешь колыбельную? – думаешь, я смогу заснуть, когда ты здесь? – прежде у теб...
  81 — 236 | J=0.0141
  44 — 306 | J=0.0109
  277 — 299 | J=0.0104
  299 — 311 | J=0.0098

================================================================================
ТЕСТ: {'window_size': 200, 'k': 4, 'num_hashes': 150, 'bands': 25}
================================================================================
Создано окон (без перекрытия): 452
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/452 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 0
Похожих пар (J>0): 0
Максимальный Jaccard: 0.0000
Похожих пар не найдено

================================================================================
ТЕСТ: {'window_size': 200, 'k': 5, 'num_hashes': 150, 'bands': 15}
================================================================================
Создано окон (без перекрытия): 452
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/452 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 0
Похожих пар (J>0): 0
Максимальный Jaccard: 0.0000
Похожих пар не найдено

================================================================================
ТЕСТ: {'window_size': 30, 'k': 2, 'num_hashes': 80, 'bands': 20}
================================================================================
Создано окон (без перекрытия): 3013
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/3013 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 179487
Похожих пар (J>0): 12594
Максимальный Jaccard: 0.1033
Топ-5 похожих пар:
  2259 — 2749 | J=0.1033
    Окно 2259: будут? – резко спросил карлайл, поворачиваясь к эдварду. лицо, которое я так люб...
    Окно 2749: – элис, нужно чем-то перевязать ее ногу! – скомандовал карлайл. – эдвард, действ...
  659 — 2833 | J=0.0967
  1302 — 1995 | J=0.0859
  2840 — 2896 | J=0.0859
  304 — 2779 | J=0.0846

================================================================================
ТЕСТ: {'window_size': 30, 'k': 3, 'num_hashes': 80, 'bands': 16}
================================================================================
Создано окон (без перекрытия): 3013
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/3013 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 19
Похожих пар (J>0): 4
Максимальный Jaccard: 0.0155
Топ-5 похожих пар:
  2326 — 2344 | J=0.0155
    Окно 2326: если дойдет до драки, то и лоран станет нашим врагом. – но нас-то больше! – есть...
    Окно 2344: – нет, не думаю, – спокойно ответила элис. младший брат снова начал ругаться. – ...
  1005 — 1990 | J=0.0060
  2344 — 2746 | J=0.0034
  2326 — 2746 | J=0.0031

================================================================================
ТЕСТ: {'window_size': 100, 'k': 4, 'num_hashes': 200, 'bands': 40}
================================================================================
Создано окон (без перекрытия): 904
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/904 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 7
Похожих пар (J>0): 6
Максимальный Jaccard: 0.0127
Топ-5 похожих пар:
  256 — 445 | J=0.0127
    Окно 256: без всяких мучений. странно, даже страшно! вторая половина дня оказалась весьма ...
    Окно 445: горечью продолжал эдвард. – мы ведь не прячемся, и если наши отношения зайдут сл...
  699 — 704 | J=0.0112
  140 — 879 | J=0.0080
  750 — 860 | J=0.0052
  321 — 445 | J=0.0026

================================================================================
ТЕСТ: {'window_size': 100, 'k': 4, 'num_hashes': 50, 'bands': 10}
================================================================================
Создано окон (без перекрытия): 904
Пример окна: стефани майер сумерки он знает, что во мраке, но свет обитает с ним. пролог раньше я не думала всерь...

MinHash (chunks):   0%|          | 0/904 [00:00<?, ?it/s]

0it [00:00, ?it/s]

Кандидатов найдено: 4
Похожих пар (J>0): 4
Максимальный Jaccard: 0.0127
Топ-5 похожих пар:
  256 — 445 | J=0.0127
    Окно 256: без всяких мучений. странно, даже страшно! вторая половина дня оказалась весьма ...
    Окно 445: горечью продолжал эдвард. – мы ведь не прячемся, и если наши отношения зайдут сл...
  140 — 879 | J=0.0080
  321 — 445 | J=0.0026
  256 — 321 | J=0.0024

In [154]:
analyze_all_results(all_results)

Успешных экспериментов: 8 из 13

Лучгий результат (макс. jaccard):
1. J=0.1033
   Окна: 30, k=2, hashes=80, bands=20
   Всего пар: 12594
2. J=0.0351
   Окна: 50, k=3, hashes=100, bands=25
   Всего пар: 163
3. J=0.0204
   Окна: 100, k=3, hashes=100, bands=25
   Всего пар: 413
4. J=0.0156
   Окна: 200, k=3, hashes=150, bands=30
   Всего пар: 117
5. J=0.0155
   Окна: 30, k=3, hashes=80, bands=16
   Всего пар: 4

 лучший по количеству пар:
1. Пар: 12594
   Окна: 30, k=2, Макс.J: 0.1033
2. Пар: 413
   Окна: 100, k=3, Макс.J: 0.0204
3. Пар: 163
   Окна: 50, k=3, Макс.J: 0.0351

лучший результат:
   Параметры: {'window_size': 30, 'k': 2, 'num_hashes': 80, 'bands': 20}
   Макс. Jaccard: 0.1033
   Всего пар: 12594

 пары:
   Окна 2259-2749 | J=0.1033
   Окна 659-2833 | J=0.0967
   Окна 1302-1995 | J=0.0859

### По метрике jaccard получаются очень низкие значения,и настоящих дубликатов можно считать не найдено.